services:
  - name: frontend
    source:
      path: frontend/
    build:
      command: npm install && npm run build
      artifacts:
        - path: build
    run:
      command: npx serve -s build
      port: 3000  # Optional: default port used by serve

  - name: backend
    source:
      path: backend/
    build:
      command: pip install -r requirements.txt
    run:
      command: uvicorn main:app --host 0.0.0.0 --port 8000
      port: 8000